import type { Metadata } from "next";
import React from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "../../@/components/ui/toaster";
import { ToastProvider } from "../../@/components/ui/toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ToastProvider>
        <body>
          <Toaster />
          <main className={inter.className}>{children}</main>
        </body>
      </ToastProvider>
    </html>
  );
}
